services:
  - type: web
    name: flowforge-api
    runtime: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
